name: EssentialsChat
main: com.earth2me.essentials.chat.EssentialsChat
version: ${version}
website: http://tiny.cc/EssentialsCommands
description: Provides chat control features for Essentials.  Requires Permissions.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally]
depend: [Essentials]
