name: EssentialsGeoIP
main: com.earth2me.essentials.geoip.EssentialsGeoIP
version: ${version}
website: http://tiny.cc/EssentialsCommands
description: Shows the country or city of a user on login and /whois.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology]
depend: [Essentials]