name: EssentialsSpawn
main: com.earth2me.essentials.spawn.EssentialsSpawn
version: ${version}
website: http://tiny.cc/EssentialsCommands
description: Provides spawn control commands, utilizing Essentials.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
depend: [Essentials]
commands:
  setspawn:
    description: Set the spawnpoint to your current position.
    usage: /<command> <group>
  spawn:
    description: Teleport to the spawnpoint.
    usage: /<command> [player]